
import java.awt.event.KeyListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Logger;
import java.net.Socket;
import java.util.StringTokenizer;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Michał
 */
public class Clients extends javax.swing.JFrame {
    String iD, idClients = "";
    DataInputStream dataInput;
    DataOutputStream dataOutput;
    DefaultListModel defaultListModel;
    
    public Clients() {
        initComponents();
    }

    Clients(String id, Socket socket) {
        iD = id;
        try{
            initComponents(); 
            defaultListModel = new DefaultListModel();
           // defaultListModel.addElement(id);- dodaje do listy nazwę usera, ale tylko tego co się loguje
            UL.setModel(defaultListModel);
            labelClientsConnect.setText(id);
            dataInput = new DataInputStream(socket.getInputStream());
            dataOutput = new DataOutputStream(socket.getOutputStream());
            new Read().start();
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
 
    class Read extends Thread {

        public void run() {
            while (true) {
                try {
                    String text = dataInput.readUTF();
                    if (!text.contains(":;.,/=?")) {
                        text = text.substring(6);
                        defaultListModel.clear();
                        StringTokenizer stringtokenizer = new StringTokenizer(text, ",");
                        while (stringtokenizer.hasMoreTokens()) {
                            String user = stringtokenizer.nextToken();
                            if (iD.equals(user)) {
                                defaultListModel.addElement(user);
                            }
                        }
                    } else {
                        msgTextArea.append("" + text + "\n");
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelClients = new javax.swing.JPanel();
        JLabelClientInfo = new javax.swing.JLabel();
        labelClientsConnect = new javax.swing.JLabel();
        SelectAllBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        msgTextField = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        UL = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chats window");

        JPanelClients.setBackground(new java.awt.Color(204, 255, 204));

        JLabelClientInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabelClientInfo.setText("Cześć:");

        labelClientsConnect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelClientsConnect.setText(".............................");

        SelectAllBtn.setText("Zaznacz wszystkich");
        SelectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAllBtnActionPerformed(evt);
            }
        });

        msgTextArea.setColumns(20);
        msgTextArea.setRows(5);
        jScrollPane1.setViewportView(msgTextArea);

        sendBtn.setBackground(new java.awt.Color(255, 51, 51));
        sendBtn.setText("Wyślij");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(UL);

        javax.swing.GroupLayout JPanelClientsLayout = new javax.swing.GroupLayout(JPanelClients);
        JPanelClients.setLayout(JPanelClientsLayout);
        JPanelClientsLayout.setHorizontalGroup(
            JPanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClientsLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(JPanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectAllBtn))
                .addGap(18, 18, 18)
                .addGroup(JPanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanelClientsLayout.createSequentialGroup()
                        .addComponent(JLabelClientInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClientsConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelClientsLayout.createSequentialGroup()
                        .addComponent(msgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(34, 34, 34))
        );
        JPanelClientsLayout.setVerticalGroup(
            JPanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClientsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(JPanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelClientInfo)
                    .addComponent(labelClientsConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(SelectAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelClientsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(JPanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(msgTextField)
                            .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowsClosing(java.awt.event.WindowEvent evt){
        String i ="mkoihgteazdcvgyhujb096785542AXTY";
        try {
            dataOutput.writeUTF(i);
            this.dispose();
        } catch (IOException ex){
            Logger.getLogger(Clients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void UserListValueChanged(javax.swing.event.ListSelectionEvent evt){
        defaultListModel.addElement(idClients);
        idClients=(String)UL.getSelectedValue();
        
    }
    
    
    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        try {
            String msg = msgTextField.getText(), mm = msg;
            String CI = idClients;

            if (!idClients.isEmpty()) {
                msg = "4344554@@@@@67667@@" + CI + ":" + mm;
                dataOutput.writeUTF(msg);
                msgTextField.setText("");
                msgTextArea.append("< YOU send to " + CI + " > " + mm + "\n");
            } 
            else {
                dataOutput.writeUTF(msg);
                msgTextField.setText("");
                msgTextArea.append("< YOY to ALL > " + mm + "\n");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Wybrany użytkownik nie istniejje");
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void SelectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAllBtnActionPerformed
        idClients="";
    }//GEN-LAST:event_SelectAllBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelClientInfo;
    private javax.swing.JPanel JPanelClients;
    private javax.swing.JButton SelectAllBtn;
    private javax.swing.JList<String> UL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelClientsConnect;
    private javax.swing.JTextArea msgTextArea;
    private javax.swing.JTextField msgTextField;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
