/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.DatagramSocketImpl;
import java.net.Socket;
import javax.swing.JOptionPane;


/**
 *
 * @author Michał
 */
public class ConnectClients extends javax.swing.JFrame {
    static String info;
    /**
     * Create new form connect new clients
     */
    public ConnectClients() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelRegister = new javax.swing.JPanel();
        idClients = new javax.swing.JTextField();
        ConnectBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zaloguj się");

        JPanelRegister.setBackground(new java.awt.Color(255, 255, 204));
        JPanelRegister.setFocusTraversalPolicyProvider(true);
        JPanelRegister.setName("ConnectBtn"); // NOI18N

        idClients.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idClients.setToolTipText("");
        idClients.setBorder(new javax.swing.border.MatteBorder(null));

        ConnectBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ConnectBtn.setText("Połącz się");
        ConnectBtn.setActionCommand("Connect");
        ConnectBtn.setBorder(new javax.swing.border.MatteBorder(null));
        ConnectBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConnectBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        ConnectBtn.setName("btConnect"); // NOI18N
        ConnectBtn.setNextFocusableComponent(ConnectBtn);
        ConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Podaj swoje imię");

        javax.swing.GroupLayout JPanelRegisterLayout = new javax.swing.GroupLayout(JPanelRegister);
        JPanelRegister.setLayout(JPanelRegisterLayout);
        JPanelRegisterLayout.setHorizontalGroup(
            JPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRegisterLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(JPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConnectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(idClients))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        JPanelRegisterLayout.setVerticalGroup(
            JPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRegisterLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(JPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idClients, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addComponent(ConnectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        idClients.getAccessibleContext().setAccessibleDescription("Wpisz swoje imię");
        ConnectBtn.getAccessibleContext().setAccessibleDescription("Połącz się");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Button - action on click
    private void ConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectBtnActionPerformed
        try {
            String id = idClients.getText();

            Socket socket = new Socket("localhost", 2089);
            DataInputStream dataInput = new DataInputStream(socket.getInputStream());
            DataOutputStream dataOutput = new DataOutputStream(socket.getOutputStream());
            dataOutput.writeUTF(id);

            String input = new DataInputStream(socket.getInputStream()).readUTF();
            if (input.equals("Jesteś już zalogowany....")) {
                JOptionPane.showMessageDialog(this, "Jesteś już zalogowany....!\n");
            } else {
                new Clients(id, socket).setVisible(true);
                this.dispose();
            } 
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ConnectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectClients().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectBtn;
    private javax.swing.JPanel JPanelRegister;
    private javax.swing.JTextField idClients;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
